# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-08-13 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
    ]
